
set(ASP_EMBEDDED_CPP_IN "${CMAKE_CURRENT_LIST_DIR}/embedded.cpp.in")
set(ASP_EMBEDDED_HPP_IN "${CMAKE_CURRENT_LIST_DIR}/embedded.hpp.in")

function(asp_embedd_binary FILE NAME)
    file(READ ${FILE} data HEX)
    if ("${data}" STREQUAL "")
        message(FATAL_ERROR "No data to embedd!")
    endif ()
    string(REGEX REPLACE "([A-Fa-f0-9][A-Fa-f0-9])" "0x\\1;" data_sep "${data}")
    string(JOIN ", " data_cpp ${data_sep})
    string(REGEX REPLACE "_+" "_" ASP_GUARD "_${NAME}_")
    string(TOUPPER ${ASP_GUARD} ASP_GUARD)
    set(GEN_DEST "${CMAKE_BINARY_DIR}/_asp_embedded/${NAME}")
    set(INC_DEST "${GEN_DEST}/inc")
    set(CPP_DEST "${GEN_DEST}/src/${NAME}.cpp")
    set(HPP_DEST "${INC_DEST}/asp/embedded/${NAME}.hpp")
    configure_file("${ASP_EMBEDDED_CPP_IN}" "${CPP_DEST}")
    configure_file("${ASP_EMBEDDED_HPP_IN}" "${HPP_DEST}")
    set(NEW_TARGET "asp_embedded_${NAME}")
    add_library(${NEW_TARGET} STATIC)
    add_library(asp_embedded::${NAME} ALIAS ${NEW_TARGET})
    target_sources(${NEW_TARGET} PRIVATE "${CPP_DEST}")
    target_include_directories(${NEW_TARGET} PUBLIC "${INC_DEST}")
endfunction()
